[package]
org="ballerinax"
name="mysql.driver"
version="1.3.0"
authors=["Ballerina"]
keywords=["Azure", "MySQL"]
repository="https://github.com/ballerina-platform/module-ballerinax-mysql.driver"
license=["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"
