[package]
org = "ballerinax"
name = "mysql.driver"
version = "1.9.0"
authors = ["Ballerina"]
keywords = ["Azure", "MySQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mysql.driver"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "./lib/mysql-connector-j-8.2.0.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mysql.driver-native"
version = "1.9.0"
path = "../native/build/libs/mysql.driver-native-1.9.0-SNAPSHOT.jar"
